apiVersion: apps/v1
kind: Deployment
metadata:
  name: q84fh-net-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: q84fh-net-app
  template:
    metadata:
      labels:
        app: q84fh-net-app
    spec:
      containers:
      - name: q84fh-net
        image: q84fh/q84fh.net:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: q84fh-net-service
  labels:
    service: q84fh-net-service
spec:
  selector:
    app: q84fh-net-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: q84fh-net-ingress
spec:
  rules:
    - host: q84fh.net
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
             name: q84fh-net-service
             port:
               number: 80
    - host: www.q84fh.net
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
             name: q84fh-net-service
             port:
               number: 80
